### ISSUE TITLE
Unable to connect to without username and password

### ISSUE THREAD

**Issue by Jimster1** [ottopaulsen/MMM-MQTT#1]
my MQTT setup doesn't require a username and password, here is my config but it doesn't display any of the payloads, can you help?

   module: 'MMM-MQTT',
    position: 'bottom_left',
    header: 'MQTT',
    config: {
        mqttUser: '',
        mqttPassword: '',
        mqttServer: '192.168.100.84',
        subscriptions: [
            {
                topic: 'groundfloor_temp',
                label: 'Groundfloor',
                decimals: 1
            },
            {
                topic: 'decking_temp',
                label: 'Garden',
                decimals: 1
            }
        ]
    }
}

**Comment by ottopaulsen** [comment]
Ok, I added support for no authentication. Just delete the two config lines for username and password. (Update the module first, of course). Please let me know the result.
