### ISSUE TITLE
Issue with dependency

### ISSUE THREAD

**Issue by Boco10** [ottopaulsen/MMM-MQTT#10]
Hello,

Have you noticed there is an issue with jsonpointer?

Uncaught ReferenceError: exports is not defined
    at jsonpointer.js:91

The line:
exports.get = get

Have you been able to fix it somehow?

Thanks

**Comment by Boco10** [comment]
Module.register("MMM-MQTT", {

    getScripts: function () {
        return [
            this.file('node_modules/jsonpointer/jsonpointer.js')
        ];
    },

This is how your file stats. Yes i just installed it today. Does the main page example works?

**Comment by Boco10** [comment]
Solved by deleting exports from the file end. Hope it does not screw up other stuff

**Comment by in-voker** [comment]
got the same problem here.

![grafik](https://user-images.githubusercontent.com/58696565/87397534-c948d480-c5b4-11ea-987c-8bd706b9fab8.png)

**Comment by in-voker** [comment]
Hi there, i freshly installed the module and got the same error
![grafik](https://user-images.githubusercontent.com/58696565/87397651-f4332880-c5b4-11ea-9367-0045788dd243.png)
