### ISSUE TITLE
certificate

### ISSUE THREAD

**Issue by badsmoke** [ottopaulsen/MMM-MQTT#11]
there is a possibility to connect to mqtt by username/password and certificate

**Comment by Silverfire9** [comment]
To avoid having to deal with permissions, the installation instructions should start with

`git clone https://github.com/ottopaulsen/MMM-MQTT`

instead of the current instruction, which uses the author's credentials.

Install worked fine for me like that.

**Comment by ottopaulsen** [comment]
Thank you, @Silverfire9. I was not aware of this difference, but I love to learn :-)
I have fixed it.

Otto
