### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by ThomasH-W** [ottopaulsen/MMM-MQTT#12]
Hi Otto, 

First thanks for the MM module - which works like a charm for me.

Is there any possibility to change the font ?
I tried using the customs.css file w/o success:
`/* file: /home/pi/MagicMirror/css/custom.css */
.MMM-MQTT.wrapper {
  font-size: 15px;
  font-weight: 300;
  font-family: "Roboto Condensed", Arial, Helvetica, sans-serif;
}`

Thomas

**Comment by ottopaulsen** [comment]
Hi Thomas.

Glad you like it.
I haven't tried to change the font, but I guess it should be easy. I do not have the time to look at it now, Maybe someone else?

Otto

**Comment by paulvanderheijden90** [comment]
Hi @ThomasH-W  And @ottopaulsen,
I use the MQTT module for display messages. I like the module very much. it is easy to set up and works right-a-way. Good job !!

Like Thomas. I would like to change some Font settings.
I ll add a picture of how it is show. 

I would like to have:
The header in a changeble font.
The MQTT text and label in the same font.
The alinement of the MQTT message. It would be nice to aline it after the Label.

**Comment by ottopaulsen** [comment]
Hi

I am sorry for the very late response, but here it is.
The header can be styled in the MQTT.css file by using locator `#module_3_MMM-MQTT > header`, for example:

```css
#module_3_MMM-MQTT > header {
    font-size: 2em;
}
```

For the 3 columns in the table, I have now added the classes:

* mqtt-label
* mqtt-value
* mqtt-suffix

so it should be possible to style them in the same file using these class names. I haven't tried myself, as my data source is out of order for the moment, so please let me know how it works :-)
