### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by slimcdk** [ottopaulsen/MMM-MQTT#13]
It does not seem that the wildcard '+' and '#' is supported.

https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/#wildcards

**Comment by ottopaulsen** [comment]
That may be correct. I am however not sure how this should be used? The module is used to display single values with a label per value. If you use wildcards, I would expect to hit multiple topics. In what kind of situation would this be useful?

**Comment by ReynirSiik** [comment]
I have two temperature sensors that have almost the same topic. Instead of presenting them on two different lines I would like to present the last received value. This gives me redundancy. Wildcards would be a neat solution for this.

**Comment by ottopaulsen** [comment]
Thank you, ReynirSiik, that is actually a good example. You could of course use the same topic on both sensors, but you may have other reasons to not do that. I will keep this request, and see if I get to look at it some time. If anyone else want to fix so wildcards work, please do.

**Comment by ottopaulsen** [comment]
Hi there. I have now added support for the + wildcard. I have barely tested it, so it would be nice if those of you that requested it could try it out and report back here.

**Comment by ottopaulsen** [comment]
Wildcard support is now optional, and turned off by default. See README for config.

Otto
