### ISSUE TITLE
Override Values

### ISSUE THREAD

**Issue by jnmcfly** [ottopaulsen/MMM-MQTT#15]
Hey, is there any possibility to override a value? E.g. window sensor delivers boolean value for topic window/isOpen. This feature would make those states more human readable.

Greetings :v:

**Comment by ottopaulsen** [comment]
Currently not, but it is a good idea.

Otto

**Comment by fmandal** [comment]
Have been wanting the same feature, so I'll see what I can do.

**Comment by adi-miller** [comment]
I just submitted a PR for something that would enable this. A general way to provide a js expression in the configuration with which you can customize the payload. I use it to convert seconds into minutes for example, but can be used for anything. 

https://github.com/ottopaulsen/MMM-MQTT/pull/26

**Comment by ottopaulsen** [comment]
Ok, I just merged and reverted @fmandal 's PR. When I tried it it did not work intuitively, nor as I expected.  I also looked ad @adi-miller PR, but using an eval function like that is way too risky. Besides, the solution is way to complex for normal people to use. Remember, this is a module not just for programmers.

I think we should create just what @jnmcfly was asking for. I am thinking about something like this, in the config:
```
              {
                topic: "house/1/doors/1",
                label: "Door",
                convertions: [
                    {from: "true", to: "Open"},
                    {from: "false", to: "Closed"},
                ]
              }
```

This will work with any values representing true and false, and can also be used for many other purposes. Not a big job to do either.

Anyone who wants to try?

**Comment by ottopaulsen** [comment]
Support for conversions is now added. Please give it a try and give feedback here.

Otto

**Comment by ottopaulsen** [comment]
I have also added support for multiplying or dividing values. Just configure `multiply` or `divide`. Please let me know if it works all right.

Otto

**Comment by Haskar** [comment]
not sure if I should write a new issue or add it here :(
conversion does not work for me :(
`subscriptions: [
                                        {
                                        topic: "cmnd/Arbeitszimmer_Licht/POWER",
                                        label: "Arbeitszimmer",
                                        maxAgeSeconds: 30,
                                        conversions: [
                                                {from: "ON", to: "AN"},
                                                {from: "OFF", to: "AUS"}
                                        ]
                                        }
                                ]
                                }
`
I am using Sonoffs with Tasmota Firmware to send the MQTT Message. 
Even with the conversion set up I see "Arbeitszimmer ON" or "Arbeitszimmer OFF" but not "Arbeitszimmer AN" oder "Arbeitszimmer AUS"

**Comment by jnmcfly** [comment]
> I have also added support for multiplying or dividing values. Just configure `multiply` or `divide`. Please let me know if it works all right.
> 
> Otto

Hey Otto, thank for adopting this idea. Works for me!
