### ISSUE TITLE
MQTT PUBLISH?

### ISSUE THREAD

**Issue by pooyasa** [ottopaulsen/MMM-MQTT#16]
Hi,
Thank you for this great module.
I was wondering if you could change this module so it can publish data as well.
I want my raspberry to transmit data to my IoT devices but I've not been able to do so,
or if there is a tutorial on that that you know and I can read and make my own module.
Thanks.

**Comment by ottopaulsen** [comment]
Hi pooyasa.

Thank you for submitting change request. I am afraid this module is not the right one for transmitting data. There are however a great number of other ways you can submit data to an MQTT message queue.  If you are running [Mosquitto](https://mosquitto.org/) on your Raspberry pi, you could use the Mosquitto clients to publish data (mosquitto_pub). These tools are easy to use to get going. However, if you want some real fun, I would recommend [Node-RED](https://nodered.org/).

Have fun!

Otto

**Comment by cybex-dev** [comment]
@pooyasa see: [MMM-MQTT-Publisher](https://github.com/cybex-dev/MMM-MQTT-Publisher)

[Discussion Thread](https://github.com/ottopaulsen/MMM-MQTT/pull/17)
