### ISSUE TITLE
MQTT- String of text.

### ISSUE THREAD

**Issue by paulvanderheijden90** [ottopaulsen/MMM-MQTT#18]
Hello,
I see in the example that you use this for displaying some values. 

Is it also posible to display just a tekst?

like: P 1 ONGEVAL Lange Bedde Breda 203092 203133 (inci-01) (GAS)

I use a MQTT Broker to broadcast some messages to some devices and I want to add these messages to the magic mirror.

**Comment by ottopaulsen** [comment]
Hi

I believe the text could be used as a value. Have you tried?

Otto

**Comment by paulvanderheijden90** [comment]
Hello Otto,
Thank you for you're reaction. Im not a programmer but im doing this for my hobby.
Yes, I tried and it worked ! so it was very easy to setup thank you for this!.

Like I comment in a other issue, ( the Font issue ) it is working but the alinement is not good.

I would like to have:
The header in a changeble font and size.
The MQTT text and label in the same font and size changeable.
The alinement of the MQTT message. It would be nice to aline it after the Label. so left alinement

I hope you can help us with this.

![Foto 21-08-19 om 14 38](https://user-images.githubusercontent.com/40613554/63437517-f46d8700-c42a-11e9-91df-9d70c2632ce5.JPG)

**Comment by ottopaulsen** [comment]
Please take a look at issue #12 . Styling should be supported now. Would be nice if you could try it out.

**Comment by paulvanderheijden90** [comment]
Otto
It works ! Thank you!!!
