### ISSUE TITLE
No data if data is old

### ISSUE THREAD

**Issue by fmandal** [ottopaulsen/MMM-MQTT#20]
It seems MagicMirror won't fetch the data if it's been written before MM started. Once the values change and the data update, the module updates - but if no data is published to MQTT, the module stays blank.

**Comment by fmandal** [comment]
To be a bit more precise: This module does not read data that's already published, it only reads data published after the module (i.e. MM) has been started. Ej

**Comment by ottopaulsen** [comment]
Hi, and thank you for asking. Your question made me examine how this really works, so I learned something today :-)

As far a I can see, it is the sender of the message that decides whether the message shall be retained or not. If the sender turns on the retain flag, the last message for each topic will be saved, and sent to any client connecting after the message was sent.

If you use Mosquitto and mosquitto_pub, you specify the -r flag. The same goes if you use MQTT.js. If you use an Arduino and the PubSubClient library, you add true as the third or fourth argument to the publish function.

So there is nothing I can do in the MMM-MQTT module to make this happen. You must see if your sources can turn on the retain-flag.
