### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by roadfox** [ottopaulsen/MMM-MQTT#24]
Any idea why the values are shown in Electron and Chrome, but not in Firefox ?
In Firefox 71.0 the header and topic names are shoen, but no values.
In chrome on a desktop and electron on the raspi where magicmirror is running the values are shown and updated fine.

thanks for the nice module!
regards
Andi

**Comment by ottopaulsen** [comment]
Well, yes, I have an idea. I suspect the regex version needed is not available on all platforms. I will make the feature using regex optional when I get the time. Hopefully that will solve the problem.

Otto

**Comment by ottopaulsen** [comment]
Hi.

I have made wildcard support optional.
Could you please download the latest version and see if it works on Firefox? (Without using wildcard support, of course).

Otto

**Comment by roadfox** [comment]
Hi Otto
Thanks allot! Works now in Firefox and still in the other browsers
