### ISSUE TITLE
Errors after Update...

### ISSUE THREAD

**Issue by Hubschra01** [ottopaulsen/MMM-MQTT#27]
Hi,
after update the MMM_MQTT Modul i get this Error and there is no connection to the MQTT Broker.
Magic mirror 2 is up to date...
I only did an update of the Modul und run 

> npm install

 at the end of the update in the modul folder.

>0|mm       | [18:12:03.228] [LOG]    MMM-MQTT: Connecting to mqtt://192.168.12.38:1883
0|mm       | [18:12:03.230] [LOG]    Whoops! There was an uncaught exception...
0|mm       | [18:12:03.232] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | [18:12:03.233] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
>/home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       |     at Class.addConfig (/home/pi/MagicMirror/modules/MMM-MQTT/node_helper.js:54:18)
0|mm       |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-MQTT/node_helper.js:102:18)
0|mm       |     at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:113:11)
0|mm       |     at Socket.emit (events.js:182:13)
0|mm       |     at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
0|mm       |     at process._tickCallback (internal/process/next_tick.js:61:11)
0|mm       | [18:12:03.231] [ERROR]  TypeError: mqtt.connect is not a function
0|mm       |     at Class.startClient (/home/pi/MagicMirror/modules/MMM-MQTT/node_helper.js:70:30)
0|mm       |     at Class.addServer (/home/pi/MagicMirror/modules/MMM-MQTT/node_helper.js:49:14)
0|mm       |     at Class.addConfig (/home/pi/MagicMirror/modules/MMM-MQTT/node_helper.js:54:18)
0|mm       |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-MQTT/node_helper.js:102:18)
0|mm       |     at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:113:11)
0|mm       |     at Socket.emit (events.js:182:13)
0|mm       |     at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
0|mm       |     at process._tickCallback (internal/process/next_tick.js:61:11)

What happend?

Thanks André

**Comment by ThomasH-W** [comment]
I did the update as well and having probably the same issue: no values were displayed. 
Due to other changes I did a system reboot the next day and MQTT worked again.

**Comment by ottopaulsen** [comment]
I just tried `npm update` in the module folder on two different computers, and got no problems. @Hubschra01 , are you still in trouble, or have you figured it out?

Otto

**Comment by spitzlbergerj** [comment]
Hi,
I have just set up MMM-MQTT and I also don't get any values displayed. But I'm not sure if my configuration is correct or if I have the same error as the previous speakers:

config:
`{
    module: 'MMM-MQTT',
    position: 'top_right',
    header: 'Tesla',
    config: {
        logging: false,
        useWildcards: false,
        mqttServers: [
            {
                address: '192.168.178.101',  // Server address or IP address
                port: '1883',          // Port number if other than default
                // user: '',          // Leave out for no user
                // password: '',  // Leave out for no password
                subscriptions: [
                    {
                        topic: 'Tesla/odometer', // Topic to look for
                        label: 'KM-Stand', // Displayed in front of value
                        suffix: 'km',         // Displayed after the value
                        decimals: 0,          // Round numbers to this number of decimals
                        maxAgeSeconds: 60,    // Reduce intensity if value is older
                    },
  `
MQTT:
`Tesla {"charging":false,"driving":false,"online":true,"sleeping":false,"speed":0,"power":0,"odometer":1163.2292917263464,"ideal_battery_range_km":224.84188164861519,"outside_temp":2.5,"battery_level":51,"charger_voltage":0,"charger_phases":0,"charger_actual_current":0,"charge_energy_added":0,"charger_power":0,"car_version":"xxxxxxx","trip_start":"00:00","trip_max_speed":0,"trip_max_power":0,"trip_duration_sec":2147483647,"trip_kwh":0.12231037867937004,"trip_avg_kwh":0,"trip_distance":0,"ts":"13:11","latitude":48.249961,"longitude":11.576138,"charge_limit_soc":80,"inside_temperature":9.8,"battery_heater":false,"is_preconditioning":false,"sentry_mode":false}`

Thanks
Josef

**Comment by spitzlbergerj** [comment]
hi, my configuration is working now. I've corrected the config.

**Comment by Hubschra01** [comment]
Hi,
actually the modul works. But i found this in the log...
`[16:53:10.566] [LOG]    MMM-MQTT: Adding server:  { address: '192.168.12.38',
  port: '1883',
  user: 'XXX',
  password: 'XXX!',
  subscriptions:
   [ { topic: 'OutDoorSensor/mess/temp',
       label: 'Temperatur',
       suffix: 'Â°C',
       decimals: 1,
       sortOrder: 10,
       maxAgeSeconds: 600 },
     { topic: 'OutDoorSensor/mess/humi',
       label: 'Luftfeuchtigkeit',
       suffix: '%rH',
       decimals: 0,
       sortOrder: 20,
       maxAgeSeconds: 600 },
     { topic: 'OutDoorSensor/mess/press',
       label: 'Luftdruck',
       suffix: 'hPa',
       decimals: 0,
       sortOrder: 30,
       maxAgeSeconds: 600 },
     { topic: 'OutDoorSensor/system/last_update',
       label: 'Last Update',
       sortOrder: 40,
       maxAgeSeconds: 600 } ] }
[16:53:10.578] [LOG]    MMM-MQTT: Starting client for:  { serverKey: '192.168.12.38:1883',
  address: '192.168.12.38',
  port: '1883',
  options: { username: 'XXX', password: 'XXX' },
  topics:
   [ 'OutDoorSensor/mess/temp',
     'OutDoorSensor/mess/humi',
     'OutDoorSensor/mess/press',
     'OutDoorSensor/system/last_update' ] }
[16:53:10.580] [LOG]    MMM-MQTT: Connecting to mqtt://192.168.12.38:1883
[16:53:10.980] [LOG]    MMM-MQTT connected to mqtt://192.168.12.38:1883
[16:53:10.984] [LOG]    MMM-MQTT: subscribing to OutDoorSensor/mess/temp,OutDoorSensor/mess/humi,OutDoorSensor/mess/press,OutDoorSensor/system/last_update
[16:53:16.138] [LOG]    Use existing news fetcher for url: http://www.tagesschau.de/xml/rss2
[16:53:16.166] [LOG]    MMM-MQTT: Adding server:  { address: '192.168.12.38',
  port: '1883',
  user: 'XXX',
  password: 'XXX!',
  subscriptions:
   [ { topic: 'OutDoorSensor/mess/temp',
       label: 'Temperatur',
       suffix: 'Â°C',
       decimals: 1,
       sortOrder: 10,
       maxAgeSeconds: 600 },
     { topic: 'OutDoorSensor/mess/humi',
       label: 'Luftfeuchtigkeit',
       suffix: '%rH',
       decimals: 0,
       sortOrder: 20,
       maxAgeSeconds: 600 },
     { topic: 'OutDoorSensor/mess/press',
       label: 'Luftdruck',
       suffix: 'hPa',
       decimals: 0,
       sortOrder: 30,
       maxAgeSeconds: 600 },
     { topic: 'OutDoorSensor/system/last_update',
       label: 'Last Update',
       sortOrder: 40,
       maxAgeSeconds: 600 } ] }
[16:53:16.168] [LOG]    MMM-MQTT: Starting client for:  { serverKey: '192.168.12.38:1883',
  address: '192.168.12.38',
  port: '1883',
  options: { username: 'XXX', password: 'XXX!' },
  topics:
   [ 'OutDoorSensor/mess/temp',
     'OutDoorSensor/mess/humi',
     'OutDoorSensor/mess/press',
     'OutDoorSensor/system/last_update',
     'OutDoorSensor/mess/temp',
     'OutDoorSensor/mess/humi',
     'OutDoorSensor/mess/press',
     'OutDoorSensor/system/last_update' ],
  client:
   MqttClient {
     options:
      { protocol: 'mqtt',
        slashes: true,
        auth: null,
        host: '192.168.12.38:1883',
        port: 1883,
        hostname: '192.168.12.38',
        hash: null,
        search: null,
        query: {},
        pathname: null,
        path: null,
        href: 'mqtt://192.168.12.38:1883',
        username: 'XXX',
        password: 'XXX!',
        keepalive: 60,
        reschedulePings: true,
        protocolId: 'MQTT',
        protocolVersion: 4,
        reconnectPeriod: 1000,
        connectTimeout: 30000,
        clean: true,
        resubscribe: true,
        clientId: 'mqttjs_18e0f1b6' },
     streamBuilder: [Function: wrapper],
     outgoingStore: Store { options: [Object], _inflights: {} },
     incomingStore: Store { options: [Object], _inflights: {} },
     queueQoSZero: true,
     _resubscribeTopics:
      { 'OutDoorSensor/mess/temp': 0,
        'OutDoorSensor/mess/humi': 0,
        'OutDoorSensor/mess/press': 0,
        'OutDoorSensor/system/last_update': 0 },
     messageIdToTopic: { '61575': [Array] },
     pingTimer:
      ReInterval {
        _callback: [Function],
        _args: [],
        _interval: [Timeout],
        reschedule: [Function],
        clear: [Function],
        destroy: [Function] },
     connected: true,
     disconnecting: false,
     queue: [],
     connackTimer:
      Timeout {
        _called: false,
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 7434,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(unrefed)]: false,
        [Symbol(asyncId)]: 1234,
        [Symbol(triggerId)]: 1213 },
     reconnectTimer: null,
     nextId: 61576,
     outgoing: {},
     _events:
      { connect: [Array],
        close: [Array],
        error: [Function],
        reconnect: [Function],
        message: [Function] },
     _eventsCount: 5,
     _maxListeners: undefined,
     stream:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: 1000,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        [Symbol(asyncId)]: 1230,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     reconnecting: false,
     pingResp: true } }
[16:53:16.187] [LOG]    MMM-MQTT: Connecting to mqtt://192.168.12.38:1883
[16:53:16.236] [LOG]    MMM-MQTT connected to mqtt://192.168.12.38:1883
[16:53:16.237] [LOG]    MMM-MQTT: subscribing to OutDoorSensor/mess/temp,OutDoorSensor/mess/humi,OutDoorSensor/mess/press,OutDoorSensor/system/last_update,OutDoorSensor/mess/temp,OutDoorSensor/mess/humi,OutDoorSensor/mess/press,OutDoorSensor/system/last_update
`

**Comment by ottopaulsen** [comment]
Good to hear it is working.
I cannot see anything wrong with the log message.
