### ISSUE TITLE
Real-Time changing font color based on Value

### ISSUE THREAD

**Issue by Ra7t0r** [ottopaulsen/MMM-MQTT#28]
Hello.
Is it possible to have an option to change the font color based on the received value?
I use MQTT and I want to change the font color to green when value is below 500, red when returned value is above 2000, purple when is above 5000 etc..
Is there a way to do this?
Thanks

**Comment by ottopaulsen** [comment]
That is a very good idea. I have done something similar in another module, so I have now made it here too. See the readme config example for an example. Please install the latest version and let me know how it works.

Otto

**Comment by Ra7t0r** [comment]
Perfect!!! It works like a charm!!
Thanks for the support, dude!
