### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by vale46n1** [ottopaulsen/MMM-MQTT#3]
Hi, how we can manage a JSON string?
Can we implement some additional code to handle this coding?

**Comment by ottopaulsen** [comment]
An interesting challenge for a lazy night. Support for JSON Pointer is added. Maybe not very failsafe, though.

**Comment by vale46n1** [comment]
Thank you very much for your job!
Anyhow, I've just tried to use the pointer but something goes wrong since I cannot get back the value.

My MQTT JSON string for the console is this one:
`tasmota/cucina/forno/sonoffpow01/tele/ENERGY = {"Time":"2018-03-03T13:11:21","Total":26.480,"Yesterday":0.050,"Today":0.028,"Period":0,"Power":2,"Factor":0.16,"Voltage":218,"Current":0.065}`

How I can recover, for instance , the Power's value?
Thanks so much

**Comment by ottopaulsen** [comment]
Not sure I understand exactly what your message looks like. What is the topic and what is the payload? The payload should start with { and end with }. Then the pointer should be /Power


Otto Paulsen
Tlf +47 99205284

(Sendt fra min mobiltelefon)

**Comment by vale46n1** [comment]
You've right. Everything works now.
Thanks so much
