### ISSUE TITLE
Feature request "show/hide when value is"

### ISSUE THREAD

**Issue by Haskar** [ottopaulsen/MMM-MQTT#30]
Hi, 

A nice feature would be to be able to only show/hide a subscription if the value of that subscription is in a specific range or has a certain value. 
i.e.: show only lights that are turned on. 

Thx :)

**Comment by ottopaulsen** [comment]
This is implemented by [PR#40](https://github.com/ottopaulsen/MMM-MQTT/pull/40).

Otto
