### ISSUE TITLE
decimals on the module

### ISSUE THREAD

**Issue by pationair** [ottopaulsen/MMM-MQTT#35]
Sorry for my Bad English...

I habe a Problem Since an Update that an Channel could not be correct displayed...

My Number came with a "," could it be, that your module only accept a "." as separation since a update?

I hope on the picture you can See what I mean...

![2020-04-06 06 51 16](https://user-images.githubusercontent.com/42006652/78524047-0c83f200-77d3-11ea-9ec6-d2c975b3056a.jpg)

**Comment by ottopaulsen** [comment]
Hi

Could you please attach that part of your config?

Otto

**Comment by pationair** [comment]
Hi, 

as link @ Pastebin https://pastebin.com/KVjcWCYk or 

{
                        					topic: 'JeelinkMQTT/BadezimmerLuftfeuchte',	// Topic to look for
                        					label: 'Badezimmer',				// Displayed in front of value
                        					suffix: '%',					// Displayed after the value				
                        					decimals: 6,					// Round numbers to this number of decimals
                        					sortOrder: 20,					// Can be used to sort entries in the same table
                        					maxAgeSeconds: 120,				// Reduce intensity if value is older
                        					divide: 100, // Divide numeric values. Alternatively use `multiply`
                        					colors: [             // Value dependent colors
                            						{ upTo: 10, value: "red", label: "red", suffix: "red" },
                            						{ upTo: 55, value: "green", label: "green", suffix: "green" },
                            						{ upTo: 65, value: "blue", label: "blue", suffix: "blue" }, // The last one is used for higher values too
                        						],
                    					},


Thanks

**Comment by ottopaulsen** [comment]
So the problem is that the Badezimmer value is missing?
Would be interesting to see how the message coming from the Badezimmer is looking. Can you show that too?
I see that you divide the value by 100, and display 0 decimals. Would expect a number though.

Otto

**Comment by pationair** [comment]
Hi,

it try sometimes until the Stats where updated after restart.

it was only a try with the divide option by myself...

The Number of decimals is 0...6 was a mistake!!!

The stat came from my Sensor like shown at the picture...

**Comment by ottopaulsen** [comment]
So is it ok now?

**Comment by pationair** [comment]
No...

The 6 was a mistake i had write...

The problem is current...

**Comment by ottopaulsen** [comment]
Hi, sorry for late response.
In order to help, I need to see what the messages on the MQTT looks like. Could you show examples on both the working messages and the non-working messages?

If you are using Mosquitto on a respberry pi, you can use the following command, adapted your config:

```
mosquitto_sub -h 10.0.0.15 -p 1883 -u username -P password -v -t "#"
```

The # gives you everything. You can add more of the path to get less.

Just paste the response in here, deleting any messages you don't want/need to show.
Use tripple ` above and below to get code formatting. It is easier to read.

**Comment by pationair** [comment]
Hey I Use MQTT.fx too Display my MQTT-Messages
![MQTT Badezimmer](https://user-images.githubusercontent.com/42006652/79365932-a07c5900-7f4b-11ea-9207-5fa68914e090.png
I  hope you can see the Message

**Comment by ottopaulsen** [comment]
Great. I can see it. So the problem may be that comma is used as decimal separator in the message. How is it in the messages that are working?

Otto

**Comment by pationair** [comment]
The 6 stats are from the same Type of Sensor Badezimmer, Gästebad, Kinderzimmer, Küche, Schlafzimmer and Wohnzimmer...these 6 dont work correctly...the Sensors are linked too a Jeelink stick and send these Message to my Openhab2 System

The 1 stat called Fortschritt, is a progress state from my 3d printer, this message came like displayed, whithout any Numbers after a comma

**Comment by ottopaulsen** [comment]
Hi

I have made a config for your decimal problem. Please update the module and try this out.
You can now set what is the decimal point in the message using the config parameter `decimalSignInMessage`.

Example:

```javascript
                    {
                        topic: 'smoky/2/inside/temperature',
                        label: 'Temp ute',
                        decimals: 1,
                        decimalSignInMessage: ",",
                        sortOrder: 20,
                        maxAgeSeconds: 60
                    },
```

Please let me know the result.

Regards,
Otto

**Comment by pationair** [comment]
Hi, 
 Really very nice Thank You!!!!
![20200424_043204](https://user-images.githubusercontent.com/42006652/80169017-9bbb4300-85e4-11ea-9f8a-a4fe1b4d2e1b.jpg)
