### ISSUE TITLE
How to disable debug log output

### ISSUE THREAD

**Issue by waldmeisterx** [ottopaulsen/MMM-MQTT#42]
If I pipe the output to a file like this
`DISPLAY=:0 npm start >> debug.log`
I always have lots of MQTT data in this log.
Is there a way to disable the debug log output of MMM-MQTT?

**Comment by ottopaulsen** [comment]
Have you set config.logging to false?
I am not sure it is working because there are bugs in the logging function.
I am currently working on a major quality rewrite, improving the code and adding tests, and I am finding some bugs in the process. I hope I can release this in a few days or maybe weeks, and I believe it will fix the issues.

**Comment by waldmeisterx** [comment]
Do you mean set logging: false globally in config.js or in the module section?
In module section the parameter is set.
If there is a new improved release these days I'm going to wait for it to be released.
It's quite a cool module I use for displaying some data from my smart home in MM.

**Comment by ottopaulsen** [comment]
I mean in the module section.
See doc.

In the latest version the logging is improved, so please try, and let me know if it is ok.

Otto

**Comment by waldmeisterx** [comment]
Ok, updated to the latest version and it seems to work. If I disable logging in config I only get the startup info, which is ok in my opinion.

The only thing I do not really like is to see my password in cleartext in the log! :-(
(here I XXXed it)

```
[25.04.2021 13:15.20.918] [LOG]   MMM-MQTT: Starting node helper
[25.04.2021 13:15.34.982] [LOG]   MMM-MQTT: Starting client for:  {
  serverKey: 'moon.fritz.box:1883mosquittouser',
  address: 'moon.fritz.box',
  port: '1883',
  options: { username: 'mosquittouser', password: 'XXX' },
  topics: [ 'sensor/wemos-schuppen-temp' ]
}
[25.04.2021 13:15.34.999] [LOG]   MMM-MQTT: Connecting to mqtt://moon.fritz.box:1883
[25.04.2021 13:15.38.561] [LOG]   MMM-MQTT connected to mqtt://moon.fritz.box:1883
[25.04.2021 13:15.38.564] [LOG]   MMM-MQTT: subscribing to sensor/wemos-schuppen-temp

```
This is logged with both settings for parameter logging.

**Comment by ottopaulsen** [comment]
That is a very good point, @waldmeisterx. I just fixed it so no password is logged.
Thanks for letting me know.

Otto

**Comment by waldmeisterx** [comment]
@ottopaulsen ok, fine. 
That looks good for me now, so I'm going to close this one as it is solved for me now. 
Thanks a lot.
