### ISSUE TITLE
Node v14 required for running MM in Server mode

### ISSUE THREAD

**Issue by stevemason** [ottopaulsen/MMM-MQTT#45]
Hi. It would appear that node v14 is a minimum requirement for this MM module when running MM in 'Server' mode (npm run server), due to the use of the 'nullish coalescing operator (??)' in utils.js

Using earlier versions of node, MM wouldn't start in server mode for me with this module enabled.

Being new to Node and MM, this took me a while to work out, so maybe it would be helpful for others if this requirement was specified in the readme? The MM project calls out node v10 explicitly, which is why I had an earlier version in the first place :-)

**Comment by stevemason** [comment]
Maybe it would be worth considering not using this operator here?

**Comment by ottopaulsen** [comment]
Thanks for letting me know. I have change this now, so the nullish coalescing operator is not used any more.

Otto

**Comment by stevemason** [comment]
Thanks Otto!

On 25/04/2021 at 9:53 AM, "Otto Paulsen"  wrote:
	Thanks for letting me know. I have change this now, so the nullish
coalescing operator is not used any more. 

	Otto

**Comment by stevemason** [comment]
@ottopaulsen I just thought I'd mention that Node.js v14 has now replaced v10 as the default version for MagicMirror (see https://forum.magicmirror.builders/topic/14987/official-recommended-node-js-version-for-mm)

**Comment by ottopaulsen** [comment]
That's nice. Thanks for letting me know.

Otto
