### ISSUE TITLE
Change font color based on state

### ISSUE THREAD

**Issue by xbmcnut** [ottopaulsen/MMM-MQTT#6]
Love you work, thank you. Very easy to implement and makes for a great wife friendly display.

Is it possible to change the color of a font based on a state? I have the following and would like the 'Closed' text green and the 'Open' text red. 

```
		{					
			module: 'MMM-mqtt',
			position: 'bottom_right',
			header: 'Garage Door Status', // This is optional
			config: {
				mqttServer: 'mqtt://ipadressofbroker', //Connection string for the server to connect to (mqtt://localhost)
				topic: 'hass/sensor/garage_status/state',
				postText: ''
			}
		},
```

**Comment by TTigges** [comment]
Change line 103 in MMM-MQTT.js from
`valueWrapper.className = "align-right bright medium";`
to
`valueWrapper.className = "align-right bright medium " + sub.value.toLowerCase();`
provided the value is just one word, not more, the cell with the value now has a class name added that's the same as the value, in your case 'closed' and you can add a line to the CSS file or your custom.css
`.MMM-MQTT .closed {
    color: green;
}
.MMM-MQTT .open{
    color: red;
}`

**Comment by xbmcnut** [comment]
@TTigges Wow, that is awesome thank you!! And yes, it is only ever one word so I'll give that a try. Would be great to draw attention to a MQTT state.

**Comment by ottopaulsen** [comment]
Assuming this is ok, so closing.
