### ISSUE TITLE
Text flashes ever 5 seconds

### ISSUE THREAD

**Issue by HaViGit** [ottopaulsen/MMM-MQTT#60]
The module is working fine but the full text flashes every about 5 seconds. The MQTT messages in question are published every 5 minutes so it doesn't seem to have anything to do with that. Does anyone have a solution?

{
    module: 'MMM-MQTT',
    position: 'bottom_right',
    header: 'ACCU&#039S',
    config: {
        logging: false,
        useWildcards: false,
        mqttServers: [
            {
                address: '192.168.2.155',
                port: '1883',
                subscriptions: [
                    {
                        topic: 'MM/Accu/Lader1',
                        label: 'Lader 1'
                    },
                    {
                        topic: 'MM/Accu/Lader2',
                        label: 'Lader 2'
                    }
                ]
            }
        ],
    }
},

**Comment by HaViGit** [comment]
Any solution...?

**Comment by ottopaulsen** [comment]
I do not have that problem, and I have no idea, sorry.

**Comment by HaViGit** [comment]
Thanks for your comment!

**Comment by HaViGit** [comment]
In general, "\xa0" can be used to add a space to the header, which works fine with all the modules I use. Unfortunately, that causes the mentioned problem with the MMM-MQTT module.

As soon as I remove "\xa0" the problem is solved and the module works properly. I know, it's strange and I can't explain it, but it's what I see happening in my setup.
