### ISSUE TITLE
Changing 'Topics'

### ISSUE THREAD

**Issue by amitdogra25** [ottopaulsen/MMM-MQTT#70]
Hello!
I'm new to Magic Mirror. Somehow managed to build one and now experimenting with various modules. I must say it is quite an interesting device. Thanks to the creators and contributors.

My Magic Mirror runs on Raspberry Pi 3B+. I was able to install **Mosquitto** MQTT Broker & Client and tested the message exchange successfully. As long as I keep the Topic description same, everything works, messages are being exchanged properly but if I try to change the Topic description, it doesn't work.

Example: Instead of **smoky/1/inside/temperature**, I would like to have **home/inside/temperature**. I changed the Topic text in **MagicMirror/config/config.js** file, subscribed to the Topic home/inside/temperature and published a test message using this Topic. Didn't work.

Can we not change the Topic description? I believe we should be. Can someone please guide me?

Thanks,
Amit

**Comment by ottopaulsen** [comment]
Of course you can change the topic. There must something else that is wrong.

**Comment by ottopaulsen** [comment]
Try to set up a subscription in a terminal window where you subscribe to everything, and then try to send messages from another terminal window. Make sure your subscription receives everything, both when you use the topic that is working and the topic that is not working. Then you can see if there are any other differences than the topic.

If this does not help, please post your config for the MMM-MQTT module here.

**Comment by amitdogra25** [comment]
It worked!!
I realised I did not restart the MagicMirror after making changes to the config file. Once it restarted everything is working fine. Thank you very much for this great module and I look forward to learning more on this technology and create new modules myself.
Have a great day! :)
