### ISSUE TITLE
Git install link broken ?

### ISSUE THREAD

**Issue by Shoyun** [ottopaulsen/MMM-MQTT#9]
Hi, i got an error installing: permission denied or not such directory. Anyone can help please ? Tks !

**Comment by ottopaulsen** [comment]
Could you please provide more information? What command is failing?

**Comment by Shoyun** [comment]
Hi Otto, here is the message (sorry it's in french)

pi@MagicMirror:~/MagicMirror/modules $ git clone git@github.com:ottopaulsen/MMM-MQTT.git
Clonage dans 'MMM-MQTT'...
Permission denied (publickey).
fatal: Impossilble de lire le dépôt distant.

Veuillez vérifier que vous avez les droits d'accès
et que le dépôt existe.

I'm sure it's a noob error, i begin with RPI sorry !

**Comment by Shoyun** [comment]
Maybe i should just clone manually the folder ?

**Comment by Shoyun** [comment]
Solved. Using `git clone https://github.com/ottopaulsen/MMM-MQTT.git` works well. Tks for this great module :)
